# Generated by Django 3.2.5 on 2021-07-08 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_profile', models.ImageField(upload_to='photos', verbose_name='Photo')),
                ('telephone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telephone')),
                ('cell', models.CharField(blank=True, max_length=11, null=True, verbose_name='Cell')),
                ('gender', models.CharField(blank=True, max_length=250, null=True, verbose_name='Gender')),
                ('marital_status', models.CharField(choices=[('S', 'Solteiro'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viúvo')], max_length=1, verbose_name='Marital Status')),
                ('school_level', models.CharField(blank=True, choices=[('FI', 'Fundamental Incompleto'), ('FC', 'Fundamental Completo'), ('MI', 'Médio Incompleto'), ('MC', 'Médio Completo'), ('SGI', 'Superior Graduação Incompleto'), ('SG', 'Superior Graduação Cursando'), ('SGC', 'Superior Graduação Completo'), ('PGI', 'Pós Graduação Incompleto'), ('PG', 'Pós Graduação Cursando'), ('PGC', 'Pós Graduação Completo'), ('M', 'Mestrado'), ('D', 'Doutorado')], max_length=3, null=True, verbose_name='School Level')),
                ('occupation', models.CharField(max_length=255, verbose_name='Occupation')),
                ('birth', models.DateField()),
                ('description', models.TextField()),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF')),
                ('postal_code', localflavor.br.models.BRPostalCodeField(max_length=9, verbose_name='CEP')),
                ('address', models.CharField(max_length=300, verbose_name='Address')),
                ('number', models.CharField(max_length=150, verbose_name='Number')),
                ('complement', models.CharField(blank=True, max_length=150, verbose_name='Complement')),
                ('district', models.CharField(max_length=250, verbose_name='District')),
                ('city', models.CharField(max_length=300, verbose_name='City')),
                ('state', localflavor.br.models.BRStateField(max_length=2, verbose_name='State')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
