# Generated by Django 3.2.5 on 2021-07-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='instagram',
            field=models.CharField(default='#', max_length=100, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin',
            field=models.CharField(default='#', max_length=100, verbose_name='Linkedin'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twiter',
            field=models.CharField(default='#', max_length=100, verbose_name='Twiter'),
        ),
    ]
